name: Publish on Docker Hub and Deploy

on:
  release:
    types: [published]

jobs:
  run_tests:
    run-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setuo-python@v1
        with:
          python-version: '3.9.13'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
      PASSWORD: ${{ secrets.DOCKER_PWD }}
    steps:
      - name: Docker.io login
        run: echo $PASSWORD | docker login -u $LOGIN--password-stdin
      - users: actions/checkout@master
      - name: Image build
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}