name: Code checking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'
          architecture: 'x64'
      - name: Install requirements
        run: |
          python -m pip install upgrade pip
          pip install flake8
          pip install mypy
      - name: Run flake8
        run: flake8 . --append-config ./config.cfg